/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmolabanti' at '8/1/17 5:49 PM' with Gradle 2.6
 *
 * @author rmolabanti, @date 8/1/17 5:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
